#!/bin/bash

#---------------
# THE IF
#---------------


# The condition Must be delimited between the [[ ]] and have a ; next the [[ ]]
# We will use the [[ ]] and not the [ ] to prevent many logic errors in scripts

# IF [[ ... ]]; then do something FI


if [[ ... ]]; then
    # ACTION TO DO
fi

# The if is going to check the condition the '...'
# And if the condition is validated or no, do the action
# To delimit the actions to do, the actions are beteween the if and the fi

# Example :

if [[ 1 == 0 ]]; then
    # ACTION TO DO
fi

# Explanations :
# If 1 = 0, then you do something
# To CHECK if the number is equal we use "==" and not the "="
# The simple "=" affect the number, and don't check the equality

#------------------------------------------------------------------------------------------

# You can check if 1 is not equal to 0 by using "!="

# Example : 

if [[ 1 != 0 ]]; then
    # ACTION TO DO
fi

# Explanations :
# If 1 is different than 0, then you do something

#------------------------------------------------------------------------------------------

# You can conbine the both, by using a ELSE

# Example : 

if [[ 1 == 2 ]]; then
    # ACTION TRUE
else
    # ACTION FALSE
fi

# Explanations :
# If 1 = 0 you say that's it's true else, you say that's false

# Note : 
# The else must be between the if and the fi, not under the fi

#------------------------------------------------------------------------------------------

# EXAMPLE : 

variable_1=1;
variable_2=2;
variable_3=3;

if [[ $variable_1 == $variable_2 ]]; then
    printf "The variable 1 and the variable 2 are the same \n"
else
    printf "The variable 1 and the variable 2 are not the same \n"

    if [[ $variable_1 == $variable_3 ]]; then
        printf "The variable 1 and the variable 3 are the same \n"
    else
        printf "The variable 1 and the variable 3 are not the same \n"
    fi
fi

# Explanations : 
# The script check if the variable 1 and 2 are the same, if they are
# It print : The variable 1 and the variable 2 are the same and stop the program
# Else if the variable 1 and 2 are not the same
# It print : The variable 1 and the variable 2 are not the same and 
# Check if the variable 1 and 3 are the same, and print if they are or not equal

#------------------------------------------------------------------------------------------