#!/bin/bash

#---------------
# THE WHILE
#---------------

# Like with the if we are gonna use the [[ ]] and not the [ ]

# The while is a methode wich wait a condition, like the if

while [[ ... ]]; do
    # ACTION TO DO
done

# The action will be delimited between the : DO and the DONE

# While the condition is active, the loop will be active, so beware...

#------------------------------------------------------------------------------------------

# For the example i will set a counter : i wich is a number initialisate at 0
# While i is not equal to 10, i will reapeat i is not equal to 10
# But if i do that, it will be inifinit, the i won't change
# So i increment i each verification with the : let "i++"
# Incrementation could be like : let "i = i + 1"
# It's the same thing but is more compact

i=0;

while [[ $i != 10 ]]; do

    # Print on scren
    printf "i != 10\n"

    # Increment i
    let "i++"
done

#------------------------------------------------------------------------------------------

# You have other conditions than : == or !=
# You have : 
# -gt : Greater Than
# -lt : Lower Than
# AND A LOT OF OTHERS 

# Example : 

i=0;
j=10;

while [[ $i -lt $j ]]; do
    let "i++"
    printf "Increment i = $i\n"
    let "j--"
    printf "Decrement j = $j\n"
done

#------------------------------------------------------------------------------------------

# You can also multiplicate conditions
# To have a condition and an other on the same time
# You have the : 
# || : Means OR
# && : Means AND

# Example :

i=0;
j=20;
k=40;

while [[ $i -lt 10 || $j -gt 10 && $k -lt 100 ]]; do
    printf "j is greater than 10 and k is lower than 100 or i is lower than 10\n"

    let "i++"
    let "j--"
    let "k=k+2"
done

#------------------------------------------------------------------------------------------