#!/bin/bash

#---------------
# THE REDIRECTIONS
#---------------

# On linux you can use a command like : ls -l 
# And copy the content into a file without create the file
# That's a redirection into a file

# Example : 

ls -l > output.txt

# Explanations : 

# A file called output.txt will be created and the content of the command
# Will be placed into the file
# But if the file already exists, it will replace her content

#------------------------------------------------------------------------------------------

# To counter that you can use : >>
# It will add the command content at the end of the file

# Example :

ls -l > output.txt

# Output.txt :
# drwxr--r--   1 fred  editors   4096  example
# -rw-r--r--   1 fred  editors  30405  EXAMPLE.sh

ls >> output.txt

# Output.txt :
# drwxr--r--   1 fred  editors   4096  example
# -rw-r--r--   1 fred  editors  30405  EXAMPLE.sh
# example
# EXAMPLE.sh
# output.txt

#------------------------------------------------------------------------------------------

# You can also show the content of a file with : cat FILE

# Example :

cat output.txt

drwxr--r--   1 fred  editors   4096  example
-rw-r--r--   1 fred  editors  30405  EXAMPLE.sh
example
EXAMPLE.sh
output.txt

# And you can redirect it AGAIN

#------------------------------------------------------------------------------------------

# To insert a line with a command you can echo your text and redirect it into your file

# Example : 

echo "Just doing an echo into output.txt" >> output.txt

# Now let's check the content :
cat output.txt

drwxr--r--   1 fred  editors   4096  example
-rw-r--r--   1 fred  editors  30405  EXAMPLE.sh
example
EXAMPLE.sh
output.txt
Just doing an echo into output.txt

#------------------------------------------------------------------------------------------